In [75]:
import os
os.environ['PATH'] += r";C:\Users\tusha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python313\Scripts"

In [76]:
!kaggle --version

Kaggle CLI 2.1.2

In [77]:
#!/bin/bash
!kaggle datasets download akshatagrawal9431/shipment-orders-dataset -f orders_data.csv

Dataset URL: https://www.kaggle.com/datasets/akshatagrawal9431/shipment-orders-dataset
License(s): CC0-1.0
orders_data.csv.zip: Skipping, found more recently modified local copy (use --force to force download)

In [78]:
import zipfile
zip_ref = zipfile.ZipFile('orders_data.csv.zip')
zip_ref.extractall()
zip_ref.close()

In [79]:
import pandas as pd

In [80]:
df = pd.read_csv("orders_data.csv")
df.head()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,01-03-2023,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,15-08-2023,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,10-01-2023,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,18-06-2022,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,13-07-2022,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [81]:
df.shape

(9994, 16)

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order Id          9994 non-null   int64
 1   Order Date        9994 non-null   object
 2   Ship Mode         9993 non-null   object
 3   Segment           9994 non-null   object
 4   Country           9994 non-null   object
 5   City              9994 non-null   object
 6   State             9994 non-null   object
 7   Postal Code       9994 non-null   int64
 8   Region            9994 non-null   object
 9   Category          9994 non-null   object
 10  Sub Category      9994 non-null   object
 11  Product Id        9994 non-null   object
 12  cost price        9994 non-null   int64
 13  List Price        9994 non-null   int64
 14  Quantity          9994 non-null   int64
 15  Discount Percent  9994 non-null   int64
dtypes: int64(6), object(10)
memory usage: 1.2+ MB

In [83]:
df1['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [84]:
df1 = pd.read_csv('orders_data.csv', na_values=['Not Available', 'unknown'])
df1['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [85]:
df1.head(2)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,01-03-2023,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,15-08-2023,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3

In [86]:
df1['Selling Price'] = df1['List Price'] - df1['List Price']*(df1['Discount Percent']/100)
df1['Selling Price']

0       254.8
1       708.1
2         9.5
3       940.8
4        19.0
        ...
9989     28.8
9990     86.4
9991    254.8
9992     29.1
9993    232.8
Name: Selling Price, Length: 9994, dtype: float64

In [87]:
df1['Profit'] = df1['Selling Price']-df1['cost price']
df1['Profit']

0        14.8
1       108.1
2        -0.5
3       160.8
4        -1.0
        ...
9989     -1.2
9990     16.4
9991     34.8
9992     -0.9
9993     22.8
Name: Profit, Length: 9994, dtype: float64

In [88]:
df1.head(2)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent,Selling Price,Profit
0,1,01-03-2023,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,254.8,14.8
1,2,15-08-2023,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,708.1,108.1

In [89]:
df1.rename(columns={'Profit':'Unit_Profit', 'Selling Price' : 'Unit_Selling_Price'},inplace=True)
df1.head()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent,Unit_Selling_Price,Unit_Profit
0,1,01-03-2023,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,254.8,14.8
1,2,15-08-2023,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,708.1,108.1
2,3,10-01-2023,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,9.5,-0.5
3,4,18-06-2022,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,940.8,160.8
4,5,13-07-2022,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,19.0,-1.0

In [90]:
df1.dtypes

Order Id                int64
Order Date             object
Ship Mode              object
Segment                object
Country                object
City                   object
State                  object
Postal Code             int64
Region                 object
Category               object
Sub Category           object
Product Id             object
cost price              int64
List Price              int64
Quantity                int64
Discount Percent        int64
Unit_Selling_Price    float64
Unit_Profit           float64
dtype: object

In [91]:
# Changing datatype of order date from object to datetime
df1.head(2)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent,Unit_Selling_Price,Unit_Profit
0,1,01-03-2023,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,254.8,14.8
1,2,15-08-2023,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,708.1,108.1

In [98]:
df1['Order Date'] = pd.to_datetime(df1['Order Date'], format='%d-%m-%Y')

In [99]:
df1.dtypes

Order Id                       int64
Order Date            datetime64[ns]
Ship Mode                     object
Segment                       object
Country                       object
City                          object
State                         object
Postal Code                    int64
Region                        object
Category                      object
Sub Category                  object
Product Id                    object
cost price                     int64
List Price                     int64
Quantity                       int64
Discount Percent               int64
Unit_Selling_Price           float64
Unit_Profit                  float64
dtype: object

In [100]:
df1.head(2)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent,Unit_Selling_Price,Unit_Profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,708.1,108.1

In [101]:
df1.drop(columns = ['cost price', 'List Price', 'Discount Percent'], inplace = True)

In [102]:
df1.head(2)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1

In [103]:
# Total profit calcluation
df1['Total Profit'] = df1['Quantity'] * df1['Unit_Profit']

In [104]:
df1.head(2)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3

In [109]:
# Exporting data frame to sql through sql alchemy library

In [124]:
!{sys.executable} -m pip install sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.49-cp312-cp312-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.0-cp312-cp312-win_amd64.whl.metadata (3.8 kB)
Collecting typing-extensions>=4.6.0 (from sqlalchemy)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Downloading sqlalchemy-2.0.49-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   -------------- ------------------------- 0.8/2.1 MB 11.2 MB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 8.4 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 4.0 MB/s eta 0:00:00
Downloading greenlet-3.5.0-cp312-cp312-win_amd64.whl (238 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Installing collected packages: typing-extensions, greenlet, sqlalchemy
Successfully installed greenlet-3.5.0 sqlalchemy-2.0.49 typing-extensions-4.15.0

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: C:\Users\tusha\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [130]:
!{sys.executable} -m pip install pyodbc

Defaulting to user installation because normal site-packages is not writeable
Collecting pyodbc
  Downloading pyodbc-5.3.0-cp312-cp312-win_amd64.whl.metadata (2.8 kB)
Downloading pyodbc-5.3.0-cp312-cp312-win_amd64.whl (70 kB)
Installing collected packages: pyodbc
Successfully installed pyodbc-5.3.0

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: C:\Users\tusha\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [126]:
import sqlalchemy as sal
print(sal.__version__)

2.0.49

In [161]:
engine = sal.create_engine('mssql://TUSHAR/project?driver=ODBC+Driver+17+for+SQL+Server')

In [162]:
conn = engine.connect()
conn

In [163]:
df1.to_sql('orders_data', con=conn, index=False, if_exists='replace')

38

In [164]:
 df1.head(2)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3

## Q1. Find top 10 highest profit generating products?

In [168]:
df1.head()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,9.5,-0.5,-1.0
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,940.8,160.8,804.0
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,19.0,-1.0,-2.0

In [169]:
df1.groupby('Product Id').sum(["Total Profit"]).sort_values(by = ["Total Profit"], ascending=False)

,Order Id,Postal Code,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit
Product Id,,,,,,
TEC-CO-10004722,28222,194875,20,59514.0,5644.0,24816.0
TEC-MA-10002412,2698,32216,6,21734.4,3624.4,21746.4
OFF-BI-10000545,57937,302599,48,18249.0,1959.0,17867.7
TEC-CO-10001449,41444,428939,38,18151.2,2631.2,15948.0
FUR-CH-10002024,44560,448062,39,21096.2,2246.2,13930.7
...,...,...,...,...,...,...
OFF-BI-10003712,46354,562879,45,124.7,-5.3,-35.7
OFF-AR-10003631,20973,277819,30,106.4,-3.6,-37.0
OFF-PA-10000143,38761,389204,29,153.8,-6.2,-39.5
OFF-BI-10002799,32515,368281,40,114.2,-5.8,-44.5
OFF-FA-10002280,54151,608473,47,251.8,-8.2,-48.2

In [174]:
df1.groupby('Product Id').sum(["Total Profit"]).sort_values(by = ["Total Profit"], ascending=False).reset_index()[['Product Id','Total Profit']].head(10)

        Product Id  Total Profit
0  TEC-CO-10004722       24816.0
1  TEC-MA-10002412       21746.4
2  OFF-BI-10000545       17867.7
3  TEC-CO-10001449       15948.0
4  FUR-CH-10002024       13930.7
5  OFF-BI-10003527       12792.9
6  TEC-PH-10001459       11481.9
7  TEC-MA-10000822       10102.3
8  FUR-TA-10000198       10015.1
9  TEC-MA-10001047        9989.0

## Q2 Create a column for total sales value for each order ---

In [178]:
df1.head(2)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit,Total Sales
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6,509.6
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3,2124.3

In [177]:
df1['Total Sales'] = df1['Unit_Selling_Price'] * df1['Quantity']
df1.head(2)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit,Total Sales
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6,509.6
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3,2124.3

## Q3 write a python code to list all distinct cities where orders have been shipped

In [180]:
df1.head(2)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit,Total Sales
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6,509.6
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3,2124.3

In [197]:
print(df1['City'].unique())
print(df1['City'].nunique())

['Henderson' 'Los Angeles' 'Fort Lauderdale' 'Concord' 'Seattle'
 'Fort Worth' 'Madison' 'West Jordan' 'San Francisco' 'Fremont'
 'Philadelphia' 'Orem' 'Houston' 'Richardson' 'Naperville' 'Melbourne'
 'Eagan' 'Westland' 'Dover' 'New Albany' 'New York City' 'Troy' 'Chicago'
 'Gilbert' 'Springfield' 'Jackson' 'Memphis' 'Decatur' 'Durham' 'Columbia'
 'Rochester' 'Minneapolis' 'Portland' 'Saint Paul' 'Aurora' 'Charlotte'
 'Orland Park' 'Urbandale' 'Columbus' 'Bristol' 'Wilmington' 'Bloomington'
 'Phoenix' 'Roseville' 'Independence' 'Pasadena' 'Newark' 'Franklin'
 'Scottsdale' 'San Jose' 'Edmond' 'Carlsbad' 'San Antonio' 'Monroe'
 'Fairfield' 'Grand Prairie' 'Redlands' 'Hamilton' 'Westfield' 'Akron'
 'Denver' 'Dallas' 'Whittier' 'Saginaw' 'Medina' 'Dublin' 'Detroit'
 'Tampa' 'Santa Clara' 'Lakeville' 'San Diego' 'Brentwood' 'Chapel Hill'
 'Morristown' 'Cincinnati' 'Inglewood' 'Tamarac' 'Colorado Springs'
 'Belleville' 'Taylor' 'Lakewood' 'Arlington' 'Arvada' 'Hackensack'
 'Saint Petersburg' 'Long Beach' 'Hesperia' 'Murfreesboro' 'Layton'
 'Austin' 'Lowell' 'Manchester' 'Harlingen' 'Tucson' 'Quincy'
 'Pembroke Pines' 'Des Moines' 'Peoria' 'Las Vegas' 'Warwick' 'Miami'
 'Huntington Beach' 'Richmond' 'Louisville' 'Lawrence' 'Canton'
 'New Rochelle' 'Gastonia' 'Jacksonville' 'Auburn' 'Norman' 'Park Ridge'
 'Amarillo' 'Lindenhurst' 'Huntsville' 'Fayetteville' 'Costa Mesa'
 'Parker' 'Atlanta' 'Gladstone' 'Great Falls' 'Lakeland' 'Montgomery'
 'Mesa' 'Green Bay' 'Anaheim' 'Marysville' 'Salem' 'Laredo' 'Grove City'
 'Dearborn' 'Warner Robins' 'Vallejo' 'Mission Viejo' 'Rochester Hills'
 'Plainfield' 'Sierra Vista' 'Vancouver' 'Cleveland' 'Tyler' 'Burlington'
 'Waynesboro' 'Chester' 'Cary' 'Palm Coast' 'Mount Vernon' 'Hialeah'
 'Oceanside' 'Evanston' 'Trenton' 'Cottage Grove' 'Bossier City'
 'Lancaster' 'Asheville' 'Lake Elsinore' 'Omaha' 'Edmonds' 'Santa Ana'
 'Milwaukee' 'Florence' 'Lorain' 'Linden' 'Salinas' 'New Brunswick'
 'Garland' 'Norwich' 'Alexandria' 'Toledo' 'Farmington' 'Riverside'
 'Torrance' 'Round Rock' 'Boca Raton' 'Virginia Beach' 'Murrieta'
 'Olympia' 'Washington' 'Jefferson City' 'Saint Peters' 'Rockford'
 'Brownsville' 'Yonkers' 'Oakland' 'Clinton' 'Encinitas' 'Roswell'
 'Jonesboro' 'Antioch' 'Homestead' 'La Porte' 'Lansing' 'Cuyahoga Falls'
 'Reno' 'Harrisonburg' 'Escondido' 'Royal Oak' 'Rockville' 'Coral Springs'
 'Buffalo' 'Boynton Beach' 'Gulfport' 'Fresno' 'Greenville' 'Macon'
 'Cedar Rapids' 'Providence' 'Pueblo' 'Deltona' 'Murray' 'Middletown'
 'Freeport' 'Pico Rivera' 'Provo' 'Pleasant Grove' 'Smyrna' 'Parma'
 'Mobile' 'New Bedford' 'Irving' 'Vineland' 'Glendale' 'Niagara Falls'
 'Thomasville' 'Westminster' 'Coppell' 'Pomona' 'North Las Vegas'
 'Allentown' 'Tempe' 'Laguna Niguel' 'Bridgeton' 'Everett' 'Watertown'
 'Appleton' 'Bellevue' 'Allen' 'El Paso' 'Grapevine' 'Carrollton' 'Kent'
 'Lafayette' 'Tigard' 'Skokie' 'Plano' 'Suffolk' 'Indianapolis' 'Bayonne'
 'Greensboro' 'Baltimore' 'Kenosha' 'Olathe' 'Tulsa' 'Redmond' 'Raleigh'
 'Muskogee' 'Meriden' 'Bowling Green' 'South Bend' 'Spokane' 'Keller'
 'Port Orange' 'Medford' 'Charlottesville' 'Missoula' 'Apopka' 'Reading'
 'Broomfield' 'Paterson' 'Oklahoma City' 'Chesapeake' 'Lubbock'
 'Johnson City' 'San Bernardino' 'Leominster' 'Bozeman' 'Perth Amboy'
 'Ontario' 'Rancho Cucamonga' 'Moorhead' 'Mesquite' 'Stockton'
 'Ormond Beach' 'Sunnyvale' 'York' 'College Station' 'Saint Louis'
 'Manteca' 'San Angelo' 'Salt Lake City' 'Knoxville' 'Little Rock'
 'Lincoln Park' 'Marion' 'Littleton' 'Bangor' 'Southaven' 'New Castle'
 'Midland' 'Sioux Falls' 'Fort Collins' 'Clarksville' 'Sacramento'
 'Thousand Oaks' 'Malden' 'Holyoke' 'Albuquerque' 'Sparks' 'Coachella'
 'Elmhurst' 'Passaic' 'North Charleston' 'Newport News' 'Jamestown'
 'Mishawaka' 'La Quinta' 'Tallahassee' 'Nashville' 'Bellingham'
 'Woodstock' 'Haltom City' 'Wheeling' 'Summerville' 'Hot Springs'
 'Englewood' 'Las Cruces' 'Hoover' 'Frisco' 'Vacaville' 'Waukesha'
 'Bakersfield' 'Pompano Beach' 'Corpus Christi' 'Redondo Beach' 'Orlando'
 'Orange' 'Lake Charles' 'Highland Park' 'Hempstead' 'Noblesville'
 'Apple Valley' 'Mount Pleasant' 'Sterling Heights' 'Eau Claire' 'Pharr'
 'Billings' 'Gresham' 'Chattanooga' 'Meridian' 'Bolingbrook' 'Maple Grove'
 'Woodland' 'Missouri City' 'Pearland' 'San Mateo' 'Grand Rapids'
 'Visalia' 'Overland Park' 'Temecula' 'Yucaipa' 'Revere' 'Conroe'
 'Tinley Park' 'Dubuque' 'Dearborn Heights' 'Santa Fe' 'Hickory'
 'Carol Stream' 'Saint Cloud' 'North Miami' 'Plantation'
 'Port Saint Lucie' 'Rock Hill' 'Odessa' 'West Allis' 'Chula Vista'
 'Manhattan' 'Altoona' 'Thornton' 'Champaign' 'Texarkana' 'Edinburg'
 'Baytown' 'Greenwood' 'Woonsocket' 'Superior' 'Bedford' 'Covington'
 'Broken Arrow' 'Miramar' 'Hollywood' 'Deer Park' 'Wichita' 'Mcallen'
 'Iowa City' 'Boise' 'Cranston' 'Port Arthur' 'Citrus Heights'
 'The Colony' 'Daytona Beach' 'Bullhead City' 'Portage' 'Fargo' 'Elkhart'
 'San Gabriel' 'Margate' 'Sandy Springs' 'Mentor' 'Lawton' 'Hampton'
 'Rome' 'La Crosse' 'Lewiston' 'Hattiesburg' 'Danville' 'Logan'
 'Waterbury' 'Athens' 'Avondale' 'Marietta' 'Yuma' 'Wausau' 'Pasco'
 'Oak Park' 'Pensacola' 'League City' 'Gaithersburg' 'Lehi' 'Tuscaloosa'
 'Moreno Valley' 'Georgetown' 'Loveland' 'Chandler' 'Helena' 'Kirkwood'
 'Waco' 'Frankfort' 'Bethlehem' 'Grand Island' 'Woodbury' 'Rogers'
 'Clovis' 'Jupiter' 'Santa Barbara' 'Cedar Hill' 'Norfolk' 'Draper'
 'Ann Arbor' 'La Mesa' 'Pocatello' 'Holland' 'Milford' 'Buffalo Grove'
 'Lake Forest' 'Redding' 'Chico' 'Utica' 'Conway' 'Cheyenne' 'Owensboro'
 'Caldwell' 'Kenner' 'Nashua' 'Bartlett' 'Redwood City' 'Lebanon'
 'Santa Maria' 'Des Plaines' 'Longview' 'Hendersonville' 'Waterloo'
 'Cambridge' 'Palatine' 'Beverly' 'Eugene' 'Oxnard' 'Renton' 'Glenview'
 'Delray Beach' 'Commerce City' 'Texas City' 'Wilson' 'Rio Rancho'
 'Goldsboro' 'Montebello' 'El Cajon' 'Beaumont' 'West Palm Beach'
 'Abilene' 'Normal' 'Saint Charles' 'Camarillo' 'Hillsboro' 'Burbank'
 'Modesto' 'Garden City' 'Atlantic City' 'Longmont' 'Davis' 'Morgan Hill'
 'Clifton' 'Sheboygan' 'East Point' 'Rapid City' 'Andover' 'Kissimmee'
 'Shelton' 'Danbury' 'Sanford' 'San Marcos' 'Greeley' 'Mansfield' 'Elyria'
 'Twin Falls' 'Coral Gables' 'Romeoville' 'Marlborough' 'Laurel' 'Bryan'
 'Pine Bluff' 'Aberdeen' 'Hagerstown' 'East Orange' 'Arlington Heights'
 'Oswego' 'Coon Rapids' 'San Clemente' 'San Luis Obispo' 'Springdale'
 'Lodi' 'Mason']
531

## Q4 Calculate total selling price and profit for all orders.

In [199]:
df1.head(2)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit,Total Sales
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6,509.6
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3,2124.3

In [200]:
# already done that in table....

## Q5 Find all the order from Technology category that were shipped using 'Second Class' ship mode, ordered by order date....

In [201]:
df1.head(2)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit,Total Sales
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6,509.6
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3,2124.3

In [202]:
df1[(df1['Category'] == 'Technology') & (df1['Ship Mode']=='Second Class')]

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit,Total Sales
19,20,2022-01-11,Second Class,Consumer,United States,San Francisco,California,94109,West,Technology,Phones,TEC-PH-10001949,3,203.7,33.7,101.1,611.1
26,27,2022-02-08,Second Class,Consumer,United States,Los Angeles,California,90049,West,Technology,Accessories,TEC-AC-10003027,3,87.3,7.3,21.9,261.9
161,162,2023-11-27,Second Class,Consumer,United States,Philadelphia,Pennsylvania,19134,East,Technology,Accessories,TEC-AC-10003657,2,47.5,7.5,15.0,95.0
181,182,2022-06-25,Second Class,Corporate,United States,Decatur,Illinois,62521,Central,Technology,Accessories,TEC-AC-10004659,7,397.7,17.7,123.9,2783.9
182,183,2022-01-10,Second Class,Home Office,United States,Monroe,Louisiana,71203,South,Technology,Phones,TEC-PH-10003273,4,475.0,5.0,20.0,1900.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9891,9892,2023-05-21,Second Class,Corporate,United States,Milwaukee,Wisconsin,53209,Central,Technology,Accessories,TEC-AC-10003116,7,116.4,6.4,44.8,814.8
9892,9893,2023-01-02,Second Class,Corporate,United States,Milwaukee,Wisconsin,53209,Central,Technology,Phones,TEC-PH-10002262,5,291.0,31.0,155.0,1455.0
9949,9950,2022-01-07,Second Class,Corporate,United States,Indianapolis,Indiana,46203,Central,Technology,Accessories,TEC-AC-10004568,3,77.6,7.6,22.8,232.8
9950,9951,2022-03-19,Second Class,Corporate,United States,Indianapolis,Indiana,46203,Central,Technology,Accessories,TEC-AC-10001714,1,38.8,-1.2,-1.2,38.8
9960,9961,2023-02-26,Second Class,Home Office,United States,Florence,Kentucky,41042,South,Technology,Accessories,TEC-AC-10002305,1,19.0,-1.0,-1.0,19.0

## Q6 Find average order value

In [204]:
df1.head(2)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit,Total Sales
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6,509.6
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3,2124.3

In [205]:
import numpy as np

In [206]:
# Order value is same  as Total Sales

In [211]:
print(np.mean(df1['Total Sales']))

1108.5979787872725

## Q7 Find city with the highest total quantity of products ordered

In [212]:
df1.head(2)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit,Total Sales
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6,509.6
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3,2124.3

In [218]:
 df1.groupby('City').sum(['Quantity'])['Quantity'].reset_index().sort_values(by=['Quantity'],ascending=False).head(1)

              City  Quantity
329  New York City      3417

## Q8 Rank the order in each region by quantity in descending order

In [219]:
df1.head(2)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit,Total Sales
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6,509.6
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3,2124.3

In [226]:
df1[['Order Id', 'Region', 'Quantity']].sort_values(by=['Region','Quantity'], ascending=[True,False])

      Order Id   Region  Quantity
660        661  Central        14
1045      1046  Central        14
7387      7388  Central        14
8074      8075  Central        14
9515      9516  Central        14
...        ...      ...       ...
9752      9753     West         1
9838      9839     West         1
9902      9903     West         1
9953      9954     West         1
9986      9987     West         1

[9994 rows x 3 columns]

## Q9 list all orders placed in the first quarter of any year(Jan to Mar), including the total cost of these orders

In [227]:
df1.head(2)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit,Total Sales
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6,509.6
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3,2124.3

In [228]:
df1['Month'] = df1['Order Date'].dt.month

In [229]:
df1.head(1)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit,Total Sales,Month
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6,509.6,3

In [231]:
df1[df1['Month'].isin([1,2,3])]

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit,Total Sales,Month
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6,509.6,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,9.5,-0.5,-1.0,19.0,1
5,6,2022-03-13,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,7,48.5,-1.5,-10.5,339.5,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,6,864.5,4.5,27.0,5187.0,1
8,9,2023-03-23,NaN,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,3,19.6,-0.4,-1.2,58.8,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9963,9964,2022-01-17,Same Day,Consumer,United States,Philadelphia,Pennsylvania,19140,East,Office Supplies,Paper,OFF-PA-10003072,2,9.7,-0.3,-0.6,19.4,1
9966,9967,2022-02-21,Second Class,Corporate,United States,Newark,Delaware,19711,East,Office Supplies,Envelopes,OFF-EN-10004483,7,105.6,5.6,39.2,739.2,2
9973,9974,2023-03-07,Standard Class,Home Office,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10004080,5,259.2,29.2,146.0,1296.0,3
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,28.8,-1.2,-3.6,86.4,2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,86.4,16.4,32.8,172.8,3

In [234]:
# Alternative by using dt.quarter
df1['Quarter'] = df1['Order Date'].dt.quarter
df1['Quarter'].head(2)

0    1
1    3
Name: Quarter, dtype: int32

In [237]:
df1[df1['Quarter'] == 1]

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit,Total Sales,Month,Quarter
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6,509.6,3,1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,9.5,-0.5,-1.0,19.0,1,1
5,6,2022-03-13,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,7,48.5,-1.5,-10.5,339.5,3,1
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,6,864.5,4.5,27.0,5187.0,1,1
8,9,2023-03-23,NaN,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,3,19.6,-0.4,-1.2,58.8,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9963,9964,2022-01-17,Same Day,Consumer,United States,Philadelphia,Pennsylvania,19140,East,Office Supplies,Paper,OFF-PA-10003072,2,9.7,-0.3,-0.6,19.4,1,1
9966,9967,2022-02-21,Second Class,Corporate,United States,Newark,Delaware,19711,East,Office Supplies,Envelopes,OFF-EN-10004483,7,105.6,5.6,39.2,739.2,2,1
9973,9974,2023-03-07,Standard Class,Home Office,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10004080,5,259.2,29.2,146.0,1296.0,3,1
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,28.8,-1.2,-3.6,86.4,2,1
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,86.4,16.4,32.8,172.8,3,1

In [238]:
# Yearly quarterly sales
df1['Year'] = df1['Order Date'].dt.year
df1['Year'].head(2)

0    2023
1    2023
Name: Year, dtype: int32

In [241]:
tempdf = df1.groupby(['Year', 'Quarter']).sum('Total Sales')['Total Sales'].reset_index()
tempdf

   Year  Quarter  Total Sales
0  2022        1    1275547.6
1  2022        2    1355326.7
2  2022        3    1343727.8
3  2022        4    1500939.2
4  2023        1    1559456.2
5  2023        2    1282878.4
6  2023        3    1308164.5
7  2023        4    1453287.8

In [243]:
tempdf[tempdf['Quarter'] == 1]

   Year  Quarter  Total Sales
0  2022        1    1275547.6
4  2023        1    1559456.2

## Q10 TOp 10 highest profit generating products

In [244]:
df1.head(2)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit,Total Sales,Month,Quarter,Year
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6,509.6,3,1,2023
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3,2124.3,8,3,2023

In [251]:
df1.groupby('Product Id').sum('Total Profit')['Total Profit'].reset_index().sort_values(by='Total Profit',ascending=False).head(10)

           Product Id  Total Profit
1614  TEC-CO-10004722       24816.0
1642  TEC-MA-10002412       21746.4
657   OFF-BI-10000545       17867.7
1604  TEC-CO-10001449       15948.0
80    FUR-CH-10002024       13930.7
776   OFF-BI-10003527       12792.9
1724  TEC-PH-10001459       11481.9
1624  TEC-MA-10000822       10102.3
318   FUR-TA-10000198       10015.1
1630  TEC-MA-10001047        9989.0

## Q11 Top 10 highest selling products in each region on acc to quantity

In [252]:
df1.head(2)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit,Total Sales,Month,Quarter,Year
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6,509.6,3,1,2023
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3,2124.3,8,3,2023

In [273]:
df1.groupby(['Region','Product Id']).sum('Quantity')['Quantity'].reset_index().sort_values(by=['Region', 'Quantity'], ascending=[True,False])

       Region       Product Id  Quantity
461   Central  OFF-BI-10000301        34
474   Central  OFF-BI-10000756        33
470   Central  OFF-BI-10000546        29
491   Central  OFF-BI-10001249        29
61    Central  FUR-CH-10002304        27
...       ...              ...       ...
5219     West  TEC-PH-10002185         1
5227     West  TEC-PH-10002447         1
5229     West  TEC-PH-10002483         1
5256     West  TEC-PH-10003357         1
5276     West  TEC-PH-10004120         1

[5298 rows x 3 columns]

## Q12 total sale in each region

In [275]:
df1.head(2)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit,Total Sales,Month,Quarter,Year
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6,509.6,3,1,2023
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3,2124.3,8,3,2023

In [278]:
df1.groupby('Region').sum('Total sales')['Total Sales'].reset_index()

    Region  Total Sales
0  Central    2387881.2
1     East    3257983.8
2    South    1966053.6
3     West    3467409.6

## Q13 Find top 5 highest selling products in each region according to sales

In [279]:
df1.head(2)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit,Total Sales,Month,Quarter,Year
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6,509.6,3,1,2023
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3,2124.3,8,3,2023

In [298]:
x=df1.groupby(['Region','Product Id']).sum('Total Sales')['Total Sales'].reset_index().sort_values(by=['Region', 'Total Sales'],ascending=[True, False])
x.groupby('Region').head(5)

       Region       Product Id  Total Sales
469   Central  OFF-BI-10000545     125827.5
1166  Central  TEC-CO-10004722      84875.0
1168  Central  TEC-MA-10000822      77509.8
488   Central  OFF-BI-10001120      55282.5
617   Central  OFF-BI-10004995      42210.0
2556     East  TEC-CO-10004722     106421.0
2565     East  TEC-MA-10001047      81549.0
1342     East  FUR-BO-10004834      66364.2
2548     East  TEC-CO-10001449      60948.0
1369     East  FUR-CH-10002024      60189.6
3691    South  TEC-MA-10002412     130406.4
3719    South  TEC-PH-10001459      73932.1
2910    South  FUR-TA-10000198      68789.9
3687    South  TEC-MA-10001127      50499.2
3192    South  OFF-BI-10003527      32029.4
5088     West  TEC-AC-10003832      61170.8
5126     West  TEC-CO-10004722      53760.0
4964     West  OFF-SU-10000151      53337.9
4099     West  FUR-TA-10003473      52669.5
3890     West  FUR-CH-10003973      43596.4

## Q14 Find month over month growth comparison for 2022 & 2023 sales eg: jan 2022 vs jan 2023

In [299]:
df1.head(2)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit,Total Sales,Month,Quarter,Year
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6,509.6,3,1,2023
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3,2124.3,8,3,2023

In [300]:
df1['Year'].unique()

array([2023, 2022], dtype=int32)

In [305]:
a = df1.groupby(['Month','Year']).sum('Total Sales')['Total Sales'].reset_index()

In [309]:
ap = a.pivot_table(index='Month', columns='Year', values='Total Sales', aggfunc = 'sum')
ap

Year       2022      2023
Month
1      437431.3  434765.5
2      444011.1  731638.8
3      394105.2  393051.9
4      476400.9  543231.5
5      413625.5  410707.9
6      465300.3  328939.0
7      375278.4  422533.7
8      534562.4  465010.3
9      433887.0  420620.5
10     601707.8  626498.3
11     451809.6  334940.6
12     447421.8  491848.9

In [310]:
ap['YOY_growth']= ap[2022] - ap[2023]
ap

Year       2022      2023  YOY_growth
Month
1      437431.3  434765.5      2665.8
2      444011.1  731638.8   -287627.7
3      394105.2  393051.9      1053.3
4      476400.9  543231.5    -66830.6
5      413625.5  410707.9      2917.6
6      465300.3  328939.0    136361.3
7      375278.4  422533.7    -47255.3
8      534562.4  465010.3     69552.1
9      433887.0  420620.5     13266.5
10     601707.8  626498.3    -24790.5
11     451809.6  334940.6    116869.0
12     447421.8  491848.9    -44427.1

## Q15 for each category which month has highest sales

In [312]:
df1.head(2)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit,Total Sales,Month,Quarter,Year
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6,509.6,3,1,2023
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3,2124.3,8,3,2023

In [340]:
s=df1.groupby(['Category','Month']).sum('Total Sales')['Total Sales'].reset_index().sort_values(by=['Category','Total Sales'], ascending=[True,False])

In [337]:
s.groupby('Category').head(1)

           Category  Month  Total Sales
1         Furniture      2     409913.9
13  Office Supplies      2     445699.6
33       Technology     10     545987.2

## Q16 Which sub category had highest growth by profit in 2023 compare to 2022

In [341]:
df1.head(2)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit,Total Sales,Month,Quarter,Year
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6,509.6,3,1,2023
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3,2124.3,8,3,2023

In [347]:
m = df1.groupby(['Sub Category','Year']).sum('Total Profit')['Total Profit'].reset_index()
m.head()

  Sub Category  Year  Total Profit
0  Accessories  2022       38798.3
1  Accessories  2023       40613.7
2   Appliances  2022       37088.7
3   Appliances  2023       17493.9
4          Art  2022        5333.0

In [350]:
n = m.pivot_table(index='Sub Category', columns='Year', values='Total Profit')
n.head()

Year             2022     2023
Sub Category
Accessories   38798.3  40613.7
Appliances    37088.7  17493.9
Art            5333.0   5079.2
Binders       40812.5  57990.3
Bookcases     25494.7  25776.1

In [356]:
n['diff'] = n[2023] - n[2022]
n.sort_values(by='diff', ascending=False).head(1)

Year             2022     2023     diff
Sub Category
Machines      34605.5  56939.8  22334.3

# Reading data in sql server through python

In [364]:
import pyodbc

# properly formatted connected string
cnxn = pyodbc.connect(
    r'Driver={ODBC Driver 17 for SQL Server};'
    r'Server=TUSHAR;'
    r'Trusted_Connection=yes;'
    r'Database=project;'
)

In [366]:
df = pd.read_sql_query('select * from orders_data', cnxn)
df.head()

C:\Users\tusha\AppData\Local\Temp\ipykernel_26004\1084758224.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query('select * from orders_data', cnxn)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,9.5,-0.5,-1.0
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,940.8,160.8,804.0
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,19.0,-1.0,-2.0

In [367]:
df.shape

(9994, 16)